import type { EmojiData } from "frimousse";

function skins(emoji: string) {
  return {
    light: `${emoji}\u{1F3FB}`,
    "medium-light": `${emoji}\u{1F3FC}`,
    medium: `${emoji}\u{1F3FD}`,
    "medium-dark": `${emoji}\u{1F3FE}`,
    dark: `${emoji}\u{1F3FF}`,
  };
}

/**
 * Emojibase doesn't provide a Turkish dataset, so this one is hand-written. A
 * real one would contain the whole set instead of a handful of emojis.
 */
export const turkishEmojiData: EmojiData = {
  locale: "tr",
  categories: [
    { index: 0, label: "Suratlar ve duygular" },
    { index: 1, label: "İnsanlar ve vücut" },
    { index: 2, label: "Hayvanlar ve doğa" },
    { index: 3, label: "Yiyecek ve içecek" },
    { index: 4, label: "Bayraklar" },
  ],
  emojis: [
    {
      emoji: "😀",
      category: 0,
      label: "sırıtan yüz",
      version: 1,
      tags: ["yüz", "gülümseme", "mutlu"],
    },
    {
      emoji: "😃",
      category: 0,
      label: "büyük gözlü sırıtan yüz",
      version: 0.6,
      tags: ["yüz", "ağız", "neşe"],
    },
    {
      emoji: "😄",
      category: 0,
      label: "gülen gözlü sırıtan yüz",
      version: 0.6,
      tags: ["yüz", "gülüş", "mutlu"],
    },
    {
      emoji: "😂",
      category: 0,
      label: "sevinç gözyaşlarıyla gülen yüz",
      version: 0.6,
      tags: ["gülme", "gözyaşı", "komik"],
    },
    {
      emoji: "🥰",
      category: 0,
      label: "kalplerle gülümseyen yüz",
      version: 11,
      tags: ["aşk", "sevgi", "kalp"],
    },
    {
      emoji: "😍",
      category: 0,
      label: "kalp gözlü yüz",
      version: 0.6,
      tags: ["aşk", "kalp", "hayranlık"],
    },
    {
      emoji: "😉",
      category: 0,
      label: "göz kırpan yüz",
      version: 0.6,
      tags: ["şaka", "göz kırpma"],
    },
    {
      emoji: "😊",
      category: 0,
      label: "gülen gözlü gülümseyen yüz",
      version: 0.6,
      tags: ["utangaç", "mutlu"],
    },
    {
      emoji: "😎",
      category: 0,
      label: "güneş gözlüklü yüz",
      version: 0.6,
      tags: ["havalı", "gözlük"],
    },
    {
      emoji: "🤔",
      category: 0,
      label: "düşünen yüz",
      version: 1,
      tags: ["düşünce", "merak"],
    },
    {
      emoji: "😭",
      category: 0,
      label: "hüngür hüngür ağlayan yüz",
      version: 0.6,
      tags: ["ağlama", "üzgün", "gözyaşı"],
    },
    {
      emoji: "😡",
      category: 0,
      label: "kızgın yüz",
      version: 0.6,
      tags: ["öfke", "sinir"],
    },
    {
      emoji: "👋",
      category: 1,
      label: "el sallama",
      version: 0.6,
      tags: ["merhaba", "selam", "hoşça kal"],
      skins: skins("👋"),
    },
    {
      emoji: "👍",
      category: 1,
      label: "başparmak yukarı",
      version: 0.6,
      tags: ["beğeni", "onay", "tamam"],
      skins: skins("👍"),
    },
    {
      emoji: "👏",
      category: 1,
      label: "alkış",
      version: 0.6,
      tags: ["tebrik", "el çırpma"],
      skins: skins("👏"),
    },
    {
      emoji: "🙏",
      category: 1,
      label: "birleştirilmiş eller",
      version: 0.6,
      tags: ["teşekkür", "dua", "lütfen"],
      skins: skins("🙏"),
    },
    {
      emoji: "🐱",
      category: 2,
      label: "kedi yüzü",
      version: 0.6,
      tags: ["kedi", "hayvan"],
    },
    {
      emoji: "🐶",
      category: 2,
      label: "köpek yüzü",
      version: 0.6,
      tags: ["köpek", "hayvan"],
    },
    {
      emoji: "🦊",
      category: 2,
      label: "tilki",
      version: 3,
      tags: ["tilki", "hayvan"],
    },
    {
      emoji: "🌷",
      category: 2,
      label: "lale",
      version: 0.6,
      tags: ["çiçek", "lale", "bahar"],
    },
    {
      emoji: "🌙",
      category: 2,
      label: "hilal",
      version: 0.6,
      tags: ["ay", "gece", "hilal"],
    },
    {
      emoji: "🍒",
      category: 3,
      label: "kiraz",
      version: 0.6,
      tags: ["meyve", "kiraz"],
    },
    {
      emoji: "🍑",
      category: 3,
      label: "şeftali",
      version: 0.6,
      tags: ["meyve", "şeftali"],
    },
    {
      emoji: "🫖",
      category: 3,
      label: "demlik",
      version: 13,
      tags: ["çay", "demlik", "içecek"],
    },
    {
      emoji: "☕",
      category: 3,
      label: "sıcak içecek",
      version: 0.6,
      tags: ["kahve", "çay", "sıcak"],
    },
    {
      emoji: "🥖",
      category: 3,
      label: "baget ekmek",
      version: 6,
      tags: ["ekmek", "fırın"],
    },
    {
      emoji: "🇹🇷",
      category: 4,
      label: "Türkiye bayrağı",
      version: 0.6,
      tags: ["türkiye", "bayrak"],
      countryFlag: true,
    },
  ],
  skinTones: {
    light: "açık ten",
    "medium-light": "orta açık ten",
    medium: "orta ten",
    "medium-dark": "orta koyu ten",
    dark: "koyu ten",
  },
};
